spring:
  profiles:
    active:
    - dev

---

server:
   port: 9090

spring:
   profiles: prod
   
   datasource:
      url: jdbc:postgresql://my-postgres:5432/mydb
      username: postgres
      password: postgres
       
---

spring:
   profiles: dev
   
   datasource:
      url: jdbc:postgresql://localhost:32793/mydb
      username: postgres
      password: postgres
   
server:
   port: 9070
   